environment:
  matrix:
    - TARGET: nightly-x86_64-pc-windows-msvc
    - TARGET: nightly-i686-pc-windows-msvc
    - TARGET: 1.10.0-x86_64-pc-windows-msvc
    - TARGET: 1.10.0-i686-pc-windows-msvc
    #- TARGET: nightly-i686-pc-windows-gnu

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:TARGET}.exe" -FileName "rust-install.exe"
  - ps: .\rust-install.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\MinGW\bin;C:\rust\bin"
  - rustc -vV
  - cargo -vV

build_script:
  - git submodule -q update --init
  - cargo build -v

test_script:
  - SET RUST_BACKTRACE=1
  - cargo test -v
